name: Linux x86_64

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Actually build the thing
      run: make -f CIMakefile
    - name: Actually test the thing
      run: make -f CIMakefile test
