name: Linux amd64 Test 

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Tests (lets hope no segmentation fault (core dumped))
      run: ./bin/libctests
