name: Linux amd64 

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Actually build the thing
      run: make -f CIMakefile
    - name: Release the artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: bin/tr24libc.a
    - name: Actually build the test
      run: make -f CIMakefile tests
